# Generated by Django 5.0.6 on 2024-05-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KOKOforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=100)),
                ('Employee_name', models.CharField(max_length=100)),
                ('Posistion', models.CharField(max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
    ]
