# Generated by Django 5.0.6 on 2024-05-19 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KOKOforms',
            new_name='kokoform',
        ),
    ]
