# Generated by Django 5.0.6 on 2024-05-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoapp', '0002_rename_kokoforms_kokoform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kokoform',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
