# Generated by Django 5.0.6 on 2024-05-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoapp', '0003_alter_kokoform_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kokoform',
            name='Company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kokoform',
            name='Employee_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kokoform',
            name='Posistion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
