# Generated by Django 5.0.6 on 2024-05-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoapp', '0004_alter_kokoform_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kokoform',
            name='ReasonOfLeave',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
