# Generated by Django 5.0.6 on 2024-05-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoapp', '0005_kokoform_reasonofleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='kokoform',
            name='CommentOnLeave',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
