# Generated by Django 5.0.6 on 2024-05-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoapp', '0006_kokoform_commentonleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='kokoform',
            name='AdequateTrainingPrograms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kokoform',
            name='JobWasChallenging',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kokoform',
            name='ManageableWorkload',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kokoform',
            name='OthersBehaviour',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kokoform',
            name='SkillsEffectivelyUsed',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kokoform',
            name='SufficientOpportunities',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kokoform',
            name='SufficientResources',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
