# Generated by Django 5.0.6 on 2024-05-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokoapp', '0008_kokoform_improvementinjobpossible_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kokoform',
        ),
    ]
